manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: hal_espressif
      remote: zephyrproject-rtos
      revision: cbf74978350266a45edbfb4508553a3990341dd2
      path: modules/hal/espressif
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 4e5cb31d32a69b3b7619ea6e0e6df3699e0d62db
      import: true

  self:
    path: zephcore
